name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: install syndie theme
        run: pip install mkdocs-windmill-dark
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
